force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/adress__c.field-meta.xml
<CustomField>
    <fullName>adress__c</fullName>
    <description>Endereço do cliente</description>
    <label>adress</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/complement__c.field-meta.xml
<CustomField>
    <fullName>complement__c</fullName>
    <description>Complementos do endereço</description>
    <label>complement</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/number_adress__c.field-meta.xml
<CustomField>
    <fullName>number_adress__c</fullName>
    <description>Numero do endereço</description>
    <label>number_adress</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/phone__c.field-meta.xml
<CustomField>
    <fullName>phone__c</fullName>
    <description>Telefone de contato do  usuário</description>
    <label>phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SearchClientController.cls
/**
 * Created by gassisal on 21/02/2020.
 */

public with sharing class SearchClientController {
    @AuraEnabled(cacheable=true)
    public static list<Client__c> searchClients(string aName){
        String lName = '%' + aName + '%';
        return [SELECT adress__c,complement__c,Email__c,Id,Name,number_adress__c,phone__c FROM Client__c WHERE Name LIKE :lName ORDER BY Name ASC NULLS FIRST];
    }
}